### PR TITLE
little code cleanup

### PR DESCRIPTION
**Pull request by deccer**
little code cleanup
started adding unit tests (they probably need refinement)
renamed projects to SharpECS.*

### CODE REVIEW

**Comment by anthony-y** [comment]
Merged, thanks Deccer.

I forgot I changed the name to ECSIsBetter at some point _cringe_ lol

**Comment by deccer** [comment]
I thought ECSIsBetter was the initial name hehe. Thanks for the merge.

**Comment by anthony-y** [comment]
There's been about 5 versions of the project and the repo and I've gone back and forth between names but SharpECS is the simplest and least cringe so I've pretty much stuck with that lol

**Comment by deccer** [comment]
gotcha :dancer:

**Pull request merged**
